using System.Collections.Generic;
using WindowsInput.Native;

namespace RemoteKeyboardUi {
  public class KeyboardMap {
    public static VirtualKeyCode TranslateKey(string key) => ITEMS[key];
    
    public static Dictionary<string, VirtualKeyCode> ITEMS = new Dictionary<string, VirtualKeyCode> {
      ["A"] = VirtualKeyCode.VK_A,
      ["Q"] = VirtualKeyCode.VK_Q,
      ["W"] = VirtualKeyCode.VK_W,
      ["E"] = VirtualKeyCode.VK_E,
      ["R"] = VirtualKeyCode.VK_R,
      ["T"] = VirtualKeyCode.VK_T,
      ["Y"] = VirtualKeyCode.VK_Y,
      ["U"] = VirtualKeyCode.VK_U,
      ["I"] = VirtualKeyCode.VK_I,
      ["O"] = VirtualKeyCode.VK_O,
      ["P"] = VirtualKeyCode.VK_P,
      ["S"] = VirtualKeyCode.VK_S,
      ["D"] = VirtualKeyCode.VK_D,
      ["F"] = VirtualKeyCode.VK_F,
      ["G"] = VirtualKeyCode.VK_G,
      ["H"] = VirtualKeyCode.VK_H,
      ["J"] = VirtualKeyCode.VK_J,
      ["K"] = VirtualKeyCode.VK_K,
      ["L"] = VirtualKeyCode.VK_L,
      ["Z"] = VirtualKeyCode.VK_Z,
      ["X"] = VirtualKeyCode.VK_X,
      ["C"] = VirtualKeyCode.VK_C,
      ["V"] = VirtualKeyCode.VK_V,
      ["B"] = VirtualKeyCode.VK_B,
      ["N"] = VirtualKeyCode.VK_N,
      ["M"] = VirtualKeyCode.VK_M,
      ["0"] = VirtualKeyCode.VK_0,
      ["1"] = VirtualKeyCode.VK_1,
      ["2"] = VirtualKeyCode.VK_2,
      ["3"] = VirtualKeyCode.VK_3,
      ["4"] = VirtualKeyCode.VK_4,
      ["5"] = VirtualKeyCode.VK_5,
      ["6"] = VirtualKeyCode.VK_6,
      ["7"] = VirtualKeyCode.VK_7,
      ["8"] = VirtualKeyCode.VK_8,
      ["9"] = VirtualKeyCode.VK_9,
      ["LEFT"] = VirtualKeyCode.LEFT,
      ["RIGHT"] = VirtualKeyCode.RIGHT,
      ["UP"] = VirtualKeyCode.UP,
      ["DOWN"] = VirtualKeyCode.DOWN,
      ["F1"] = VirtualKeyCode.F1,
      ["F2"] = VirtualKeyCode.F2,
      ["F3"] = VirtualKeyCode.F3,
      ["F4"] = VirtualKeyCode.F4,
      ["F5"] = VirtualKeyCode.F5,
      ["F6"] = VirtualKeyCode.F6,
      ["F7"] = VirtualKeyCode.F7,
      ["F8"] = VirtualKeyCode.F8,
      ["F9"] = VirtualKeyCode.F9,
      ["F10"] = VirtualKeyCode.F10,
      ["F11"] = VirtualKeyCode.F11,
      ["F12"] = VirtualKeyCode.F12,
      ["SHIFT"] = VirtualKeyCode.SHIFT,
      ["CTRL"] = VirtualKeyCode.CONTROL,
      ["TAB"] = VirtualKeyCode.TAB,
      ["ALT"] = VirtualKeyCode.MENU,
      ["ESC"] = VirtualKeyCode.ESCAPE,
      ["SPACE"] = VirtualKeyCode.SPACE,
    };
  }
}